name = "hub-cf"
main = "worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "."
binding = "ASSETS"

[vars]
GOOGLE_CLIENT_ID = "325888692252-898ld1tl4l8e1d1hv2v42ds7kjdunp7f.apps.googleusercontent.com"
LINKEDIN_CLIENT_ID = "77csy2pgtctq9s"

[[d1_databases]]
binding = "DB"
database_name = "nesen-d1"
database_id = "bfafca56-dbc9-49d5-a6cc-137ec0ee06c9"

# [vars]
# JWT_SECRET = "your-secret-here"